export type EntryType = {
  Dossier: string;
  'Numéro de mission': string;
  Version: string;
  'Statut mission': string;
  'Type de service': string;
  Date: string;
  'Heure début mission': string;
  'Heure fin mission': string;
  'Début de service': string;
  'Fin de service': string;
  'Nom client': string;
  Passagers: string;
  Pax: string;
  'Prise en charge': string;
  Itinéraire: string;
  'Km début': string;
  'Km fin': string;
  Destination: string;
  'Note au chauffeur': string;
  'Tout type de véhicule\n\n': string;
  'Modèle de véhicule': string;
  Voiture: string;
  Partenaire: string;
  'Partenaire Fixe': string;
  'Partenaire mobile': string;
  'Prénom chauffeur': string;
  'Nom chauffeur': string;
  'chauffeur mobile 1': string;
  'chauffeur mobile 2': string;
  'Heure inclus au devis': string;
  'Km inclus au devis': string;
  'Facture n°': string;
  Libellé: string;
  "Prix d'achat ht": string;
  'Montant HT total des frais additionnels': string;
  'Prix de vente HT': string;
  'Montant TVA': string;
  'Prix de vente TTC': string;
  'Commentaire chauffeur': string;
  Référence: string;
  'N° Vol': string;
  Terminal: string;
  'Ville provenance': string;
  'Vol heure': string;
  'Vol avance': string;
  'Heures réelles chauffeur (format 01:00)': string;
  'Stand by': string;
  'Forfait net chauffeur': string;
  'Processus Shuttle': string;
  'Commentaire dossier': string;
  'Référence client du dossier': string;
  'Légende de mission': string;
  'Montant Ht annulé': string;
  'Montant Ttc annulé': string;
  'Nom du contact client': string;
};
